modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GPL"

[[mods]]
modId="project_light"
version="1.0.0"
displayName="ProjectLight"
authors="momosensei"
description='''ProjectLight.'''

[[dependencies.project_light]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.project_light]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"